# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Verify that the build folder has been created and contains files
- script: |
    ls -la $(System.DefaultWorkingDirectory)/build
  displayName: 'Verify build output'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'PersonalAzurePrac'  # Replace with your Azure subscription name
    appName: 'TaskifyAzurePrac'  # Replace with your Azure App Service name
    package: '$(System.DefaultWorkingDirectory)/build'
    appType: 'webApp'
